#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

export PLEX_MEDIA_SERVER_INFO_MODEL=$(uname -m)
export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$(uname -r)

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

echo "Starting Plex Media Server."
redirect_cmd exec s6-setuidgid abc \
	/usr/lib/plexmediaserver/Plex\ Media\ Server
