#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
	echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
	umask ${UMASK_SET}
fi

export PLEX_MEDIA_SERVER_INFO_MODEL=$(uname -m)
export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$(uname -r)

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

echo "Starting Plex Media Server."
redirect_cmd exec s6-setuidgid abc \
	/usr/lib/plexmediaserver/Plex\ Media\ Server
